### ISSUE TITLE
Discord Hook Grabber xddddd

### ISSUE THREAD

**Issue by schwungvoll** [0xSxZ/Veerus#2]
**Don't download this.** Obfuscated code. Classic obfuscation. I guess from Rdimo (yeah I'm not that big fat Discord Mod kid that I know all that stuff), but it's pretty obvious a rat. Don't fall for this bad trick. And I guess his Account is also an alt. Please don't be so dumb... and open it. The classic Icon for compiling .py files. And he said it has a Miner feature. In Python..? I don't know man haha.. Doesn't look like python, but a compiled .py file. Mhhh. Obvious a Discord Webhook Grabber hahahaha
![image](https://user-images.githubusercontent.com/96620548/193335218-247b3672-5efc-4dd0-afba-5ada79efaa09.png)
Just don't. Fucking don't. 

And to the owner, _show us the source code if it's no virus :)_

**Bad hacker lmfao hahahahah**

***Prove us wrong hahah :)***

**Comment by 0xSxZ** [comment]
just pick the rat.exe and use pyinstractor bro. The rat is a classic rat not working anymore tho.

**Comment by 0xSxZ** [comment]
i didn't noticed but bro is watching at .exe file and wondering why it's not readable 💀💀💀💀

**Comment by 0Zombie** [comment]
Bro you can simply see the code of some exe files but urs is obfuscated and what did you notice? That its a grabber? Show us the code dude... It's a fucking compiled python file lmao and ur saying that it has a miner function

**Comment by 0Zombie** [comment]
nigga stfu hope your fucking entire family dies

**Comment by 0Zombie** [comment]
its obv a rat/grabber when youe execute nothing happens

**Comment by 0Zombie** [comment]
+ error + you can simply see code of some exe files.. but not from this one.. hmmm. obfuscated??? yyeeess!!! GRABBER!

**Comment by 0xSxZ** [comment]
yes it's a rat bro, it's the thing you send to the men you wanna grab 💀💀💀

**Comment by 0xSxZ** [comment]
> 

HUAHAHAHAHAHHAHAHAHAHHA LMAO DONT TALK ANYMORE PLS

**Comment by 0Zombie** [comment]
DUDE TF ARE YOU DUMB?? I MEAN YOU PUT IN YOUR GRABBER TO STEAL PPLS STUFF

**Comment by 0Zombie** [comment]
r4t.exe
executed
nothing happened

ran it on a sandbox

**Comment by 0xSxZ** [comment]
💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀💀

bro you need to execute it like that : r4t.exe bot_token
