### ISSUE TITLE
.

### ISSUE THREAD

**Issue by gumbobr0t** [0xSxZ/Veerus#4]

**Comment by dc203eec615967a8f6928725d2ad3c65** [comment]
ofc its malware, that is literally the entire point of this repo

**Comment by Dinosaurum** [comment]
> ofc its malware, that is literally the entire point of this repo

nah bro its a discord logger? are oyu dumb? can't you read? but he probably dual hooked it

**Comment by dc203eec615967a8f6928725d2ad3c65** [comment]
the entire point of this repo is to be a piece of malware, a info stealer, a miner, and a rat, you're retarded

**Comment by Dinosaurum** [comment]
you are retarded. you can't get my point right? I FUCKIGN KNOW ITS MALWARE AND A LOGGER AND A MINER AND RAT YOUR FUCKING BRAINDEAD ASS KID BUT HE DUAL HOOKED AND INFECTED THE R4T.EXE IN RELEASES WITH HIS OWN SHIT

NOW DIE
